### PR TITLE
use FB_ORCA_AGENT from purple-facebook

### PR DESCRIPTION
**Pull request by gmartsenkov**
Fixes facebook authentication error - `User must verify their account on www.facebook.com (405)`
I don't understand why it fixes it really, but had the idea because i could login without a problem with pidgin.

### CODE REVIEW

**Comment by saligari** [comment]
I can see that the maintainer is currently looking for someone else to take over, is there anyone who has write access?

This is critical, probably solves #196 as well as #195. This can lead to complete lock for someone's facebook account so I'd say this is quite urgent to fix. I hope someone will see this and merge, personally I just found out about this project.

**Comment by jackblk** [comment]
It seems to happen again today. @gmartsenkov can you share the method to get a new correct user agent?

**Comment by gmartsenkov** [comment]
@jackblk Well previously I got the Agent from https://github.com/dequis/purple-facebook, searching for `FB_API_AGENT` but doesn't look like it has changed since this PR

**Comment by miztizm** [comment]
Hello guys , what `FB_API_AGENT` do you use ?
this one ? 
`#define FB_ORCA_AGENT "[FBAN/Orca-Android;FBAV/537.0.0.31.101;FBPN/com.facebook.orca;FBLC/en_US;FBBV/52182662]"`

i tested most of them from [here](https://user-agents.net/applications/facebook-app): including windows, andorid, ios and it the same problem, that makes me think that its not related to user agent.

**Pull request closed without merging**
