### PR TITLE
Bump the FB_ORCA_AGENT version once again

### PR DESCRIPTION
**Pull request by mrc0mmand**
Recently FB started returning ERROR_QUEUE_UNDERFLOW upon login (again).
Given the similarity to #180, the fix seemed quite straightforward, and
it indeed is - bumping the client version fixes the login issue.

Fixes: #207

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Also, the second commit bumps the Ubuntu version in Travis CI to Focal to get around the build failure caused by a missing dependency (python3-m2crypto).

**Comment by dequis** [comment]
Thanks!

The CI situation is kinda fucked in general, tbh. Still not sure if obs works.

**Comment by mrc0mmand** [comment]
> The CI situation is kinda fucked in general, tbh. Still not sure if obs works.

Unfortunately, [it doesn't seems so](https://travis-ci.org/github/bitlbee/bitlbee-facebook/builds/755339906#L697):
```
$ .travis/obs.sh
Server returned an error: HTTP Error 401: Unauthorized
Error getting meta for project 'home:[secure]' package 'bitlbee-facebook'
```

But hey, at least it builds!

**Comment by Thaodan** [comment]
Bump the version of the module also?

**Pull request merged**
